Repository NREL/rex, pull requests merged in 2025-05, with the labels that each got.

#213 Bump dask dep
  pyproject.toml
  rex/version.py
Labels: chore, dependencies, enhancement

#214 Relax depdencny requirements
  pyproject.toml
  rex/version.py
Labels: dependencies, enhancement

#215 Add suggestions for `xarray .open_mfdataset` parameters
  examples/xarray/README.rst
  examples/xarray/daily_agg.ipynb
  rex/external/rexarray.py
  tests/h5pyd_tests.py
  tests/test_rexarray.py
Labels: documentation, enhancement

#216 Add fallback if accessing HSDS fails
  rex/utilities/utilities.py
  rex/version.py
  tests/test_utilities.py
Labels: enhancement, p-high

#217 Updating Wind SAM CSV Formatting output
  .github/workflows/h5pyd_tests.yml
  pyproject.toml
  rex/renewable_resource.py
  rex/resource_extraction/resource_extraction.py
  rex/sam_resource.py
  tests/test_resource_extraction.py
  tests/test_resource_hh.py
  tests/test_resource_invalid.py
  tests/test_sam_resource.py
Labels: breaking, bugfix, p-high
